### ISSUE TITLE
Constant vhost errors from server

### ISSUE THREAD

**Issue by skykingisepic** [progrium/qmux#28]
These are just from a single client connection:
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50518: i/o timeout
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50524: i/o timeout
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50528: i/o timeout
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50550: i/o timeout
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50552: i/o timeout
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50558: i/o timeout
Failed to extract vhost name: read tcp 45.76.255.14:4415->173.44.95.183:50562: i/o timeout

Client and Server running on two different linux systems

Server DNS has wildcard subdomains set
Server bound to 0.0.0.0
Server port 4415

Running client on two different PCs simultaneously
Client connects to server with port 3415
Running quick test using mini-httpd listening on port 3415 with simple 2-line output html file

Browsers using generated address to connect to other PC successfully - html displayed

Plan is to use groktunnel to do crypto wallet transfers (EPIC Cash) to wallet on LAN behind router (using ngrok currently but don't trust them to keep the free access going so we need our own option).

Load issue with server throwing constant errors even if sending to /dev/nul ?

Can Server handle thousands of concurrent client connections?

I tried a wallet transfer from a mining pool to local wallet (these transactions were fine with localtunnel). It's a very small data stream. The server threw a Failed to extract vhost name: EOF and ended the session. Client shows EOF and Exit. So it looks like groktunnel is very http specific and will not allow just the http header then an open tcp tunnel like localtunnel. Will have to use that instead.

**Comment by progrium** [comment]
Yea or ngrok. groktunnel is just an example!
